POST https://jsonplaceholder.typicode.com/posts
Content-type: application/json; charset=UTF-8

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}
###
GET https://jsonplaceholder.typicode.com/posts/1